### PR TITLE
Typings for TypeScript

### LINKED ISSUE #81: Support for TypeScript?
Are there types for TypeScript?
Package `@types/node-gd` not exists. I don't see `*.ts` files in the repository.

### PR DESCRIPTION
**Pull request by vladislav805**
Hi again.
I have prepared a file with types, but there are a few places where I'm not sure/don't understand.
* [x] What returns `gd.getClip()`?
* [x] What returns `gd.colorDeallocate()`?
* [x] What returns `gd.cropAuto()`? 
* [x] What returns `gd.Image#compare()`?
* [x] What returns `gd.Image#file()`?

And, if you can, find a couple of minutes, check everything else.

I tried to install the `vladislav805/node-gd` with types directly to my project - it seems to work.

Thanks a lot.
Closes #81

### CODE REVIEW

**Comment by y-a-v-a** [comment]
Hi @vladislav805 , awesome work!
Let me try to answer your questions:
getClip, as per https://github.com/y-a-v-a/node-gd/blob/f25834456fa87d78c8d64d8fb69052b48e700455/src/node_gd.cc#L1064 will return an object with 4 properties:
```javascript
{
  x1: 0,
  y1: 0,
  x2: 0,
  y2: 0
}
```

**Comment by y-a-v-a** [comment]
I think `colorDeallocate` just return s `this`, which the image you called `colorDeallocate` up on.

**Comment by y-a-v-a** [comment]
And `cropAuto` returns a new gd.Image object, a JS wrapper around the libgd image.

**Comment by y-a-v-a** [comment]
`compare` returns a Number, as I read from https://github.com/y-a-v-a/node-gd/blob/f25834456fa87d78c8d64d8fb69052b48e700455/src/node_gd.cc#L2150 but I have never used it and I have no clear idea on what to expect that number to be. I'd have to look at the source code of libGD to know...

**Comment by y-a-v-a** [comment]
And `gd.Image#file()` returns a Promise, as per line https://github.com/y-a-v-a/node-gd/blob/f25834456fa87d78c8d64d8fb69052b48e700455/src/node_gd_workers.cc#L372

Hope this helps! Keep up the good work, and thank you in advance. If you think you're done, let's see how the build goes, and I will release a new minor version.
Regards,
Vincent

**Comment by vladislav805** [comment]
Now it's generally good. Autocomplete works.

image

I checked the rest of the methods, in parallel, found errors in the documentation and sent them in pull request #83.

@y-a-v-a, I guess it's done

**Comment by y-a-v-a** [comment]
FYI just released 2.1.1, eventually decided to make it a patch release. Updated contributors file and files entry in package.json.
See also https://www.npmjs.com/package/node-gd and https://github.com/y-a-v-a/node-gd/releases
Thank you for your contributions!
Vincent

**Pull request merged**
