### PR TITLE
using latest nan to fix node6 depreciation errors

### LINKED ISSUE #20: node 6.1 - v8::ObjectTemplate::Set() with non-primitive values is deprecated
After upgrade to node v6 I get the following error:

```
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================
bla bla bla

==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: Gd::Image::Init(v8::Local<v8::Object>)
 3: Gd::Init(v8::Local<v8::Object>)
 4: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: 0x7065aa
 7: 0x70690c
 8: 0x1bacde30961b
```

It seems that everything is working now, but I'm afraid that it can stop working in near future.

### PR DESCRIPTION
**Pull request by chriwup**
Fixes #20 (and thus speeds up execution time)

### CODE REVIEW

**Comment by y-a-v-a** [comment]
Will review next week, when back from vacation. 👍🏻

**Comment by y-a-v-a** [comment]
Merged and bumped version to 1.2.1, also published in NPM.
FYI: Builds fail in TravisCI but that's more of an issue related to http://llvm.org/ than to node-gd.

**Comment by chriwup** [comment]
Thanks, though in the meantime I got another build issue, for which I have issued a PR ( #22 )

**Comment by y-a-v-a** [comment]
@ghost FYI: for issue #36 I've renamed the `stable` branch to the more common `master`.

**Pull request merged**
